//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Calculadora_Fraccion.java
//  @ Date : 24/08/2021
//  @ Author : Oscar Flores
//  @ Objetivo : Calculadora orientada a objetos de una división

import java.io.*;
import java.util.*;

public class Calculadora_Fraccion {
	private float numerador;
	private float denominador;
   
   
	//Método constructor para crear un nuevo objeto de la clase Calculadora_Fraccion
   public Calculadora_Fraccion(float numerador, float denominador) {
	   this.numerador=numerador;
      this.denominador=denominador;
	}
	
   
   //Método para retornar el resultado de la división
   public float calDivision() {
	   return numerador/denominador;
	}
	
	//Método para desplegar el resultado directamente 
   public String toString() {
	   return "El resultado de la división es: "+calDivision();
	}
   
}

class Principal{
   public static void main(String args[]){
      float numerador=leerNum();
      float denominador=leerDen();
      Calculadora_Fraccion frac1=new Calculadora_Fraccion(numerador, denominador);
      System.out.println(frac1);
   
   }
   
   //Método para leer el numerador
   public static float leerNum(){
      Scanner s=new Scanner(System.in);
      System.out.println("Ingrese numerador");
      return s.nextFloat();
   }
   
   //Método para leer el denominador, verifica que no es igual a 0
   public static float leerDen(){
      Scanner s=new Scanner(System.in);
      float denominador=0;
      while(denominador==0){
         System.out.println("Ingrese denominador, este no puede ser igual a 0");
         denominador=s.nextFloat();
         if(denominador==0)
            System.out.println("El denominador no puede ser 0");
      }
      return denominador;
   }

}